integralfamilies:
  - name: "hxb"
    loop_momenta: [k1,k2]
    top_level_sectors: [b1111111110000]
    permutation_option: 1
    propagators:
      - [ "k1", 0]
      - [ "k1 + p1", 0]
      - [ "k1 + p1 + p2", 0]
      - [ "k2 - k1", 0]
      - [ "k2 + p1 + p2 ", 0]
      - [ "k2 + p1 + p2 + p3 ", 0]
      - [ "k2 + p1 + p2 + p3 + p4 ", 0]
      - [ "k2 + p1 + p2 + p3 + p4 + p5", mt2]
      - [ "k2", 0]
      - [ "k1 + p3", 0]
      - [ "k1 + p4", 0]
      - [ "k1 + p5", 0]
      - [ "k2 + p1", 0]
