kinematics:
  incoming_momenta: [p1,p2,p3,p4,p5,p6]
  outgoing_momenta: []
  momentum_conservation: [p6,-p1-p2-p3-p4-p5]
  kinematic_invariants:
     - [s12, 2]
     - [s23, 2]
     - [s34, 2]
     - [s45, 2]
     - [s56, 2]
     - [s16, 2]
     - [s123, 2]
     - [s234, 2]
     - [s345, 2]
     - [mt2, 2]
  scalarproduct_rules:
     - [[p1,p1], 0]
     - [[p2,p2], 0]
     - [[p3,p3], 0]
     - [[p4,p4], 0]
     - [[p5,p5], mt2]
     - [[p1,p2], s12/2]
     - [[p1,p3], (-s12 + s123 - s23)/2]
     - [[p1,p4], (-s123 + s23 - s234 + s56)/2]
     - [[p1,p5], (mt2 - s16 + s234 - s56)/2]
     - [[p2,p3], s23/2]
     - [[p2,p4], (-s23 + s234 - s34)/2]
     - [[p2,p5], (s16 - s234 + s34 - s345)/2]
     - [[p3,p4], s34/2]
     - [[p3,p5], (-s34 + s345 - s45)/2]
     - [[p4,p5], (-mt2 + s45)/2]
