kinematics:
  incoming_momenta: [p1,p2,p3,p4,p5]
  outgoing_momenta: []
  momentum_conservation: [p5,-p1-p2-p3-p4]
  kinematic_invariants:
     - [s12, 2]
     - [s23, 2]
     - [s34, 2]
     - [s45, 2]
     - [s15, 2]
     - [mTsq, 2]
     - [qsq, 2]
  scalarproduct_rules:
     - [[p1,p1], mTsq]
     - [[p2,p2], qsq]
     - [[p3,p3], mTsq]
     - [[p4,p4], 0]
     - [[p1,p2], -(mTsq/2) - qsq/2 + s12/2]
     - [[p1,p3], qsq/2 - s12/2 - s23/2 + s45/2]
     - [[p1,p4], -(s15/2) + s23/2 - s45/2]
     - [[p2,p3], -(mTsq/2) - qsq/2 + s23/2]
     - [[p2,p4], mTsq/2 + s15/2 - s23/2 - s34/2]
     - [[p3,p4], -(mTsq/2) + s34/2]

