kinematics:
  incoming_momenta: [p1,p2,p3,p4]
  outgoing_momenta: []
  momentum_conservation: [p4,-p1-p2-p3]
  kinematic_invariants:
     - [s12, 2]
     - [s16, 2]
     - [s345, 2]
     - [mTsq, 2]
  scalarproduct_rules:
     - [[p1,p1], 0]
     - [[p2,p2], 0]
     - [[p3,p3], s345]
     - [[p1,p2], s12/2]
     - [[p1,p3], mTsq/2 - s12/2 - s16/2]
     - [[p2,p3], s16/2 - s345/2]

