kinematics:
  incoming_momenta: [p1,p2,p3,p4]
  outgoing_momenta: []
  momentum_conservation: [p4,-p1-p2-p3]
  kinematic_invariants:
     - [s23, 2]
     - [s45, 2]
     - [s15, 2]
     - [mTsq, 2]
  scalarproduct_rules:
     - [[p1,p1], mTsq]
     - [[p2,p2], s23]
     - [[p3,p3], 0]
     - [[p1,p2], -(mTsq/2) - s23/2 + s45/2]
     - [[p1,p3], -(s15/2) + s23/2 - s45/2]
     - [[p2,p3], s15/2 - s23/2]

