integralfamilies:
  - name: "TTH"
    loop_momenta: [k1,k2]
    top_level_sectors: [b11111111000]
    permutation_option: 1
    propagators:
      - [ "k1", 0]
      - [ "k1 + p1", mTsq]
      - [ "k1 + p1 + p2", mTsq]
      - [ "k1 + p1 + p2 + p3", 0]
      - [ "k2+k1", 0]
      - [ "k2", 0]
      - [ "k2 - p1 - p2 - p3 - p4", 0]
      - [ "k2 - p1 - p2 - p3", 0]
      - [ "k1 + p1 + p2 + p3 + p4", 0]
      - [ "k2 - p1 - p2", mTsq]
      - [ "k2 - p1", mTsq]
